/** Declaration file generated by dts-gen */

export function OriTest(options: any): void;

export function install(t: any): any;

export namespace OriTest {
    const cid: number;

    const entryName: string;

    const extendOptions: {
        mixins: {
            data: any;
        }[];
        name: string;
    };

    const superOptions: {
        components: {
            KeepAlive: {
                abstract: boolean;
                created: any;
                destroyed: any;
                methods: {
                    cacheVNode: any;
                };
                mounted: any;
                name: string;
                props: {
                    exclude: any[];
                    include: any[];
                    max: any[];
                };
                render: any;
                updated: any;
            };
            Transition: {
                abstract: boolean;
                name: string;
                props: {
                    appear: any;
                    appearActiveClass: any;
                    appearClass: any;
                    appearToClass: any;
                    css: any;
                    duration: any[];
                    enterActiveClass: any;
                    enterClass: any;
                    enterToClass: any;
                    leaveActiveClass: any;
                    leaveClass: any;
                    leaveToClass: any;
                    mode: any;
                    name: any;
                    type: any;
                };
                render: any;
            };
            TransitionGroup: {
                beforeMount: any;
                methods: {
                    hasMove: any;
                };
                props: {
                    appear: any;
                    appearActiveClass: any;
                    appearClass: any;
                    appearToClass: any;
                    css: any;
                    duration: any[];
                    enterActiveClass: any;
                    enterClass: any;
                    enterToClass: any;
                    leaveActiveClass: any;
                    leaveClass: any;
                    leaveToClass: any;
                    moveClass: any;
                    name: any;
                    tag: any;
                    type: any;
                };
                render: any;
                updated: any;
            };
        };
        directives: {
            model: {
                componentUpdated: any;
                inserted: any;
            };
            show: {
                bind: any;
                unbind: any;
                update: any;
            };
        };
        filters: {
        };
    };

    function component(id: any, definition: any): any;

    function directive(id: any, definition: any): any;

    function extend(extendOptions: any): any;

    function filter(id: any, definition: any): any;

    function install(t: any): void;

    function mixin(mixin: any): any;

    function use(plugin: any, ...args: any[]): any;

    namespace options {
        const directives: {
            model: {
                componentUpdated: any;
                inserted: any;
            };
            show: {
                bind: any;
                unbind: any;
                update: any;
            };
        };

        const filters: {
        };

        const mixins: {
            data: any;
        }[];

        const name: string;

        const staticRenderFns: any[];

        function data(): any;

        function render(): any;

        namespace components {
            // Circular reference from ori_ui_demo0.OriTest.options.components
            const OriTest: any;

            namespace KeepAlive {
                // Too-deep object hierarchy from ori_ui_demo0.OriTest.options.components.KeepAlive
                const abstract: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.options.components.KeepAlive
                const created: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.options.components.KeepAlive
                const destroyed: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.options.components.KeepAlive
                const methods: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.options.components.KeepAlive
                const mounted: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.options.components.KeepAlive
                const name: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.options.components.KeepAlive
                const props: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.options.components.KeepAlive
                const render: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.options.components.KeepAlive
                const updated: any;

            }

            namespace Transition {
                // Too-deep object hierarchy from ori_ui_demo0.OriTest.options.components.Transition
                const abstract: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.options.components.Transition
                const name: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.options.components.Transition
                const props: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.options.components.Transition
                const render: any;

            }

            namespace TransitionGroup {
                // Too-deep object hierarchy from ori_ui_demo0.OriTest.options.components.TransitionGroup
                const beforeMount: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.options.components.TransitionGroup
                const methods: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.options.components.TransitionGroup
                const props: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.options.components.TransitionGroup
                const render: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.options.components.TransitionGroup
                const updated: any;

            }

        }

    }

    namespace sealedOptions {
        const directives: {
            model: {
                componentUpdated: any;
                inserted: any;
            };
            show: {
                bind: any;
                unbind: any;
                update: any;
            };
        };

        const filters: {
        };

        const mixins: {
            data: any;
        }[];

        const name: string;

        function data(): any;

        namespace components {
            // Circular reference from ori_ui_demo0.OriTest.sealedOptions.components
            const OriTest: any;

            namespace KeepAlive {
                // Too-deep object hierarchy from ori_ui_demo0.OriTest.sealedOptions.components.KeepAlive
                const abstract: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.sealedOptions.components.KeepAlive
                const created: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.sealedOptions.components.KeepAlive
                const destroyed: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.sealedOptions.components.KeepAlive
                const methods: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.sealedOptions.components.KeepAlive
                const mounted: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.sealedOptions.components.KeepAlive
                const name: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.sealedOptions.components.KeepAlive
                const props: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.sealedOptions.components.KeepAlive
                const render: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.sealedOptions.components.KeepAlive
                const updated: any;

            }

            namespace Transition {
                // Too-deep object hierarchy from ori_ui_demo0.OriTest.sealedOptions.components.Transition
                const abstract: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.sealedOptions.components.Transition
                const name: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.sealedOptions.components.Transition
                const props: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.sealedOptions.components.Transition
                const render: any;

            }

            namespace TransitionGroup {
                // Too-deep object hierarchy from ori_ui_demo0.OriTest.sealedOptions.components.TransitionGroup
                const beforeMount: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.sealedOptions.components.TransitionGroup
                const methods: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.sealedOptions.components.TransitionGroup
                const props: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.sealedOptions.components.TransitionGroup
                const render: any;

                // Too-deep object hierarchy from ori_ui_demo0.OriTest.sealedOptions.components.TransitionGroup
                const updated: any;

            }

        }

    }

}

